name: Automated Data Logger

on:
  # This trigger is perfect for your external cron job
  workflow_dispatch:

jobs:
  capture-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # --- THIS IS THE FIX ---
      # This new step downloads the actual browser needed by Playwright.
      # The --with-deps flag is crucial for Linux runners.
      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Run the Data Logger script
        run: python logger.py

      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update data logs and state"
          file_pattern: "data_logs/*.json current_state.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"